#pragma once

#include <filesystem>
#include <string>

#include "core/maxine/effects/maxine_effect.h"
#include "core/maxine/nvcv_api.h"
#include "core/maxine/vfx_api.h"

namespace studiocast::maxine::effects {

// Wrapper for Maxine VFX "Video Relighting" / "Relighting" effect.
//
// Local contract (StudioCast):
// - Requires a matte (Au8) generated by Green Screen in the same pipeline.
// - Produces a relit foreground image (BGRu8).
// - Background compositing/blending is handled by the pipeline (not the
// effect).
class VfxRelightingEffect final : public IVfxEffect {
public:
  struct Config {
    // HDRI/environment map file path. If empty, the effect may fail depending
    // on the Maxine build; StudioCast will try to provide a default.
    std::filesystem::path hdri_path;

    // Optional direction control (pan/yaw angle in degrees).
    float direction_pan_degrees = 0.0f;
  };

  VfxRelightingEffect(maxine::vfx::VfxApi *vfx, maxine::NvcvApi *nvcv,
                      std::filesystem::path model_dir);
  ~VfxRelightingEffect() override;

  VfxRelightingEffect(const VfxRelightingEffect &) = delete;
  VfxRelightingEffect &operator=(const VfxRelightingEffect &) = delete;

  const char *Id() const override { return "relighting"; }
  const char *DisplayName() const override { return "Video Relighting"; }

  bool Initialize(std::string *error);

  // Configure from canonical settings.
  bool
  Configure(const studiocast::video::effects::BroadcastCameraEffects &settings,
            std::string *error) override;

  // Runs relighting on `frame.nvcv_gpu` using `frame.matte_gpu`.
  // The relit foreground output is stored in an internal GPU NvCVImage.
  NvCV_Status Process(studiocast::video::GpuFrame &frame,
                      std::string *error) override;
  bool SetExternalCudaStream(maxine::CUstream stream,
                             std::string *error) override;
  void InvalidateBindings() noexcept override;

  const maxine::NvCVImage *OutputGpu() const {
    return output_ready_ ? &output_gpu_ : nullptr;
  }

  maxine::CUstream cuda_stream() const { return stream_; }

  const Config &config() const { return cfg_; }
  void SetConfig(const Config &cfg);

private:
  bool EnsureEffectCreated(std::string *error);
  bool ApplyConfigLocked(std::string *error);
  bool EnsureStreamBound(std::string *error);
  bool EnsureOutputImage(unsigned width, unsigned height, std::string *error);
  bool BindMatte(const maxine::NvCVImage *matte, std::string *error);

  void Destroy();

  maxine::vfx::VfxApi *vfx_ = nullptr;
  maxine::NvcvApi *nvcv_ = nullptr;
  std::filesystem::path model_dir_;

  maxine::vfx::NvVFX_Handle handle_ = nullptr;
  maxine::CUstream stream_ = nullptr;
  maxine::CUstream external_stream_ = nullptr;
  bool external_stream_selected_ = false;
  bool own_stream_ = false;
  bool stream_bound_ = false;

  Config cfg_{};
  bool cfg_dirty_ = true;

  maxine::NvCVImage output_gpu_{};
  bool output_ready_ = false;
  bool output_allocated_ = false;
  const maxine::NvCVImage *bound_input_ = nullptr;
  const maxine::NvCVImage *bound_matte_ = nullptr;
  maxine::NvCVImage *bound_output_ = nullptr;
  const char *matte_selector_ = nullptr;
  const char *output_selector_ = nullptr;
  unsigned bound_width_ = 0;
  unsigned bound_height_ = 0;
};

} // namespace studiocast::maxine::effects
